import { BlendType } from './ColorBlend';
export declare class Color {
    r: number;
    g: number;
    b: number;
    a: number;
    constructor(r: any, g: number, b: number, a?: number);
    hex(): string;
    static rgb(hex: string): Color;
    blend(color: Color, blendType: BlendType): Color;
    static blend(color1: Color, color2: Color, blendType: BlendType): Color;
    invert: Color;
    luminance: number;
    grayscale: number;
    maxColorComponent: number;
    static indianRed: Color;
    static lightCoral: Color;
    static salmon: Color;
    static darkSalmon: Color;
    static crimson: Color;
    static red: Color;
    static firebrick: Color;
    static darkRed: Color;
    static pink: Color;
    static lightPink: Color;
    static hotPink: Color;
    static deepPink: Color;
    static mediumViolet: Color;
    static paleViolet: Color;
    static lightSalmon: Color;
    static coral: Color;
    static tomato: Color;
    static orangeRed: Color;
    static darkOrange: Color;
    static orange: Color;
    static gold: Color;
    static yellow: Color;
    static lightYellow: Color;
    static lemonChiffon: Color;
    static lightGoldenRodYellow: Color;
    static papayWhip: Color;
    static moccasin: Color;
    static peachPuff: Color;
    static paleGoldenRod: Color;
    static khaki: Color;
    static darkKhaki: Color;
    static lavender: Color;
    static thistle: Color;
    static plum: Color;
    static violet: Color;
    static orchid: Color;
    static fuchsia: Color;
    static magenta: Color;
    static mediumOrchid: Color;
    static mediumPurple: Color;
    static rebeccaPurple: Color;
    static blueViolet: Color;
    static darkViolet: Color;
    static darkOrchid: Color;
    static darkMagenta: Color;
    static purple: Color;
    static indigo: Color;
    static slateBlue: Color;
    static darkSlateBlue: Color;
    static greenYellow: Color;
    static chartreuse: Color;
    static lawnGreen: Color;
    static lime: Color;
    static limeGreen: Color;
    static paleGreen: Color;
    static lightGreen: Color;
    static mediumSpringGreen: Color;
    static springGreen: Color;
    static mediumSeaGreen: Color;
    static seaGreen: Color;
    static forestGreen: Color;
    static green: Color;
    static darkGreen: Color;
    static yellowGreen: Color;
    static oliveDrab: Color;
    static olive: Color;
    static darkOliveGreen: Color;
    static mediumAquaMarine: Color;
    static darkSeaGreen: Color;
    static lightSeaGreen: Color;
    static darkCyan: Color;
    static teal: Color;
    static cyan: Color;
    static lightCyan: Color;
    static paleTurquoise: Color;
    static aquaMarine: Color;
    static turquoise: Color;
    static mediumTurquoise: Color;
    static darkTurquoise: Color;
    static cadetBlue: Color;
    static steelBlue: Color;
    static lightSteelBlue: Color;
    static powderBlue: Color;
    static lightBlue: Color;
    static skyBlue: Color;
    static lightSkyBlue: Color;
    static deepSkyBlue: Color;
    static dodgerBlue: Color;
    static cornFlowerBlue: Color;
    static mediumSlateBlue: Color;
    static royalBlue: Color;
    static blue: Color;
    static mediumBlue: Color;
    static darkBlue: Color;
    static navy: Color;
    static midnighBlue: Color;
    static cornSilk: Color;
    static blanchedAlmond: Color;
    static bisque: Color;
    static navajoWhite: Color;
    static wheat: Color;
    static burlyWood: Color;
    static tan: Color;
    static rosyBrown: Color;
    static sandyBrown: Color;
    static goldenRod: Color;
    static darkGoldenRod: Color;
    static peru: Color;
    static chocolate: Color;
    static saddleBrown: Color;
    static sienna: Color;
    static brown: Color;
    static maroon: Color;
    static white: Color;
    static snow: Color;
    static honeyDew: Color;
    static mintCream: Color;
    static azure: Color;
    static aliceBlue: Color;
    static ghostWhite: Color;
    static whiteSmoke: Color;
    static seaShell: Color;
    static beige: Color;
    static oldLace: Color;
    static floralWhite: Color;
    static ivory: Color;
    static antiqueWhite: Color;
    static linen: Color;
    static lavenderBlush: Color;
    static mistyRose: Color;
    static gainsBoro: Color;
    static lightGray: Color;
    static silver: Color;
    static darkGray: Color;
    static gray: Color;
    static dimGray: Color;
    static lightSlateGray: Color;
    static slateGray: Color;
    static darkSlateGray: Color;
    static black: Color;
}
